BAZARKA.WEB/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BAZARKA.CORE.DAL;
using BAZARKA.CORE.Models;
using BAZARKA.CORE.ViewModels;

namespace BAZARKA.WEB.Controllers
{
    public class ShopController : Controller
    {
        ShippingServices oShippingService = null;
        TaxServices oTaxService = null;
        AllRepository<CustomerInvoice> oCustInvoiceRepo = null;

        public ActionResult Checkout()
        {
            return View();
        }

        public ActionResult Basket()
        {
            List<Product> model = null;
            List<VM_CartProducts> ProductSKUs = GetCartProducts();
            if (ProductSKUs != null)
            {
                List<string> SKUs = ProductSKUs.Select(x => x.sku).ToList();
                model = ProductServices.Instance.GetProducts(SKUs);
            }
            return View(model);
        }

        public ActionResult MiniBasket()
        {
            List<Product> model = null;
            List<VM_CartProducts> CartProducts = GetCartProducts();
            if (CartProducts != null && CartProducts.Count > 0)
            {
                var productSKUs = CartProducts.Select(x => x.sku).ToList();
                model = ProductServices.Instance.GetProducts(productSKUs);
                for (int i = 0; i < model.Count; i++)
                {
                    model[i].UnitsInStock = CartProducts.Where(x => x.sku == model[i].SKU).Select(x => x.quantity).FirstOrDefault();
                }
            }
            return PartialView(model);
        }

        #region Cart
        public bool SetCartProducts(List<VM_CartProducts> CartProducts)
        {
            bool retval = false;
            try
            {
                if (CartProducts != null && CartProducts.Count() > 0)
                {
                    HttpCookie cookie = Request.Cookies["CartProducts"];
                    cookie.Value = string.Empty;
                    for (int i = 0; i < CartProducts.Count(); i++)
                    {
                        if (i == 0)
                        {
                            cookie.Value += CartProducts[i].sku + "|" + CartProducts[i].quantity.ToString();
                        }
                        else
                        {
                            cookie.Value += "-";
                            cookie.Value += CartProducts[i].sku + "|" + CartProducts[i].quantity.ToString();
                        }
                    }
                    Response.SetCookie(cookie);
                    retval = true;
                }
                else
                {
                    HttpCookie cookie = Request.Cookies["CartProducts"];
                    cookie.Value = string.Empty;
                    Response.SetCookie(cookie);
                    retval = true;
                }
            }
            catch (Exception ex)
            {
                retval = false;
            }
            return retval;
        }

        public List<VM_CartProducts> GetCartProducts()
        {
            List<VM_CartProducts> oCartProducts = null;
            List<string> oProd = new List<string>();
            VM_CartProducts oCartProduct = null;
            var CartProductsCookie = Request.Cookies["CartProducts"];
            if (CartProductsCookie != null && CartProductsCookie.Value.Count() > 0)
            {
                oCartProducts = new List<VM_CartProducts>();
                oProd = CartProductsCookie.Value.Split('-').Select(x => x.ToString()).ToList();
                foreach (var obj in oProd)
                {
                    oCartProduct = new VM_CartProducts();
                    int StrtPos = obj.IndexOf("|") + 1;
                    string Qty = obj.Substring(StrtPos);
                    string SKU = obj.Substring(0, StrtPos - 1);
                    oCartProduct.quantity = Convert.ToInt32(Qty);
                    oCartProduct.sku = SKU;
                    oCartProducts.Add(oCartProduct);
                }
            }
            return oCartProducts;
        }

        public bool EmptyCartProducts()
        {
            bool retval = false;
            try
            {
                var CartProductsCookie = Request.Cookies["CartProducts"];
                if (CartProductsCookie != null && CartProductsCookie.Value.Count() > 0)
                {
                    CartProductsCookie.Value = null;
                    Response.SetCookie(CartProductsCookie);
                    retval = true;
                }
                else
                {
                    retval = true;
                }
            }
            catch (Exception ex)
            {
                retval = false;
            }
            return retval;
        }

        [HttpPost]
        public JsonResult AddProduct(string productSku)
        {
            string retMessage = string.Empty;
            bool success = false;
            try
            {
                List<VM_CartProducts> ExistingCartProducts = GetCartProducts();
                if (ExistingCartProducts != null && ExistingCartProducts.Count() > 0)
                {
                    if (ExistingCartProducts.Exists(x => x.sku.ToUpper() == productSku.ToUpper()))
                    {
                        retMessage = "Product Already in Cart!";
                    }
                    else
                    {
                        VM_CartProducts NewProduct = new VM_CartProducts();
                        NewProduct.sku = productSku;
                        NewProduct.quantity = 1;
                        ExistingCartProducts.Add(NewProduct);
                        success = SetCartProducts(ExistingCartProducts);
                        if (success)
                        {
                            retMessage = "Product Added to cart!";
                        }
                        else
                        {
                            retMessage = "Error occured!";
                        }
                    }
                }
                else
                {

                    HttpCookie cookie = new HttpCookie("CartProducts");
                    cookie.Name = "CartProducts";
                    cookie.Path = "/";
                    cookie.Value += productSku + "|1";
                    cookie.Expires = DateTime.Now.AddDays(30);
                    Response.Cookies.Add(cookie);
                    success = true;
                }
            }
            catch (Exception ex)
            {
                success = false;
                retMessage = "Error occured";
            }
            return Json(new { success = success, responseText = retMessage }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult RemoveProduct(string productSku)
        {
            string retMessage = string.Empty;
            bool success = false;
            try
            {
                List<VM_CartProducts> CartProducts = GetCartProducts();
                if (CartProducts != null && CartProducts.Count > 0)
                {
                    if (CartProducts.Exists(x => x.sku == productSku))
                    {
                        VM_CartProducts obj = CartProducts.Where(x => x.sku == productSku).SingleOrDefault();
                        if (obj != null)
                        {
                            CartProducts.Remove(obj);
                        }
                        success = SetCartProducts(CartProducts);
                        if (success)
                        {
                            retMessage = "Product Removed";
                        }
                        else
                        {
                            retMessage = "Error occured";
                        }
                    }
                }
                else
                {
                    retMessage = "Cart is empty!";
                    success = false;
                }
            }
            catch (Exception ex)
            {
                success = false;
                retMessage = "Error occured";
            }
            return Json(new { success = success, responseText = retMessage }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult UpdateProduct(string productSku, int qty)
        {
            string retMessage = string.Empty;
            bool success = false;
            try
            {
                List<VM_CartProducts> CartProducts = GetCartProducts();
                VM_CartProducts ProductToUpdate = CartProducts.Where(x => x.sku == productSku).FirstOrDefault();
                if (CartProducts != null && CartProducts.Count > 0 && ProductToUpdate != null)
                {
                    int Index = CartProducts.IndexOf(ProductToUpdate);
                    CartProducts[Index].quantity = qty;
                    success = SetCartProducts(CartProducts);
                }
            }
            catch (Exception ex)
            {
                success = false;
            }
            return Json(new { success = success, responseText = retMessage }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        private bool EmptyOrderSummary()
        {
            bool retval = false;
            try
            {
                VM_OrderSummary.EstimatedTotal = 0;
                VM_OrderSummary.MerchandiseSubTotal = 0;
                VM_OrderSummary.Shipping = 0;
                VM_OrderSummary.Tax = 0;
                VM_OrderSummary.TaxPercentApplied = 0;
                retval = true;
            }
            catch(Exception ex)
            {
                retval = false;
            }
            return retval;
        }

        [HttpGet]
        public ActionResult PlaceOrder()
        {
            return PartialView(new VM_PlaceOrder());
        }

        [HttpPost]

BAZARKA.WEB/Views/Shop/Basket.cshtml
@model List<Product>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Master.cshtml";
}
@{
    int Total = 0;
    int Shipping = 0;
    int Tax = 0;
}
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <div class="col-lg-12 m-0">
                <h3 class="myh1"> My Basket </h3>
                <h3 class="myh3">  </h3>
            </div>
            <div class="col-lg-12 greyborder mt-1 m-0">
                <h4> No Discounts For Now! </h4>
                <p>  </p>
            </div>
            <div class="col-lg-12 greyborder mt-1 m-0">
                <div class="border-bottom">
                    <div class="RenderProducts">
                        @{
                            Html.RenderAction("MiniBasket", "Shop");
                        }
                    </div>
                </div>
            </div>
            <!-- Similar Product Start -->
        </div>
        @{
            Html.RenderAction("OrderSummary", "Shop");
        }
    </div>
    <!-- row closed -->
    @{
        Html.RenderAction("RecommendedForYou", "Home");
    }
</div>
<script type="text/javascript">
    $(document).on('click', '.btdelete', function () {
        var productSku = $(this).attr('data-id');
        $.ajax({
            type: "POST",
            url: '@Url.Action("RemoveProduct", "Shop")',
            data: { productSku: productSku },
            dataType: "json",
            success: function (response) {
                alert(response.responseText);
                MyFunc();
            },
            error: function (response) {
                alert(response.responseText);
            }
        });
    });

    function MyFunc()
    {
        var mydiv = document.getElementById('RenderProducts');
    }
</script>

BAZARKA.WEB/Views/Shop/Basket.mobile.cshtml
@model List<Product>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Master.cshtml";
}
@{
    int Total = 0;
    int Shipping = 0;
    int Tax = 0;
}




<div class="col-12 bg-white m-0">
    <h3 class="myh1"> My Basket </h3>


</div>

@{
    Html.RenderAction("MiniBasket", "Shop");
}





@{
    Html.RenderAction("OrderSummary", "Shop");
}

BAZARKA.WEB/Views/Shop/Checkout.cshtml
@{
    ViewBag.Title = "Checkout";
    Layout = "~/Views/Shared/Master.cshtml";
}
@model BAZARKA.CORE.ViewModels.VM_PlaceOrder
<div class="container">
    <div class="row">
        <div class="col-lg-8" id="PlaceOrderView">
            @{ 
                Html.RenderAction("PlaceOrder", "Shop");
            }
            <div>
                @Html.ActionLink("Back to Products", "Index")
            </div>
        </div>
        <!-- right column closed -->
        @{
            Html.RenderAction("OrderSummary", "Shop");
        }
        <!-- left column closed -->
    </div>
    <!-- row closed -->
</div>  
<script>

</script>

BAZARKA.WEB/Views/Shop/MiniBasket.cshtml
@model List<Product>
@{
    if (Model != null && Model.Count() > 0)
    {
        <div class="m-0 p-0"> <h4 class="m-0 p-0"> You have @Model.Count() items.</h4></div>
    }
    else
    {
        <div class="m-0 p-0"> <h4 class="m-0 p-0"> Your basket is empty </h4> </div>
    }
}
<div class="myScroll">
    @if (Model != null && Model.Count() > 0)
    {
        foreach (var product in Model)
        {
            <div id="@product.SKU">
                <div class="row bg-white m-1 greyborder">
                    <div class="col-lg-2">
                        <img src="@product.ProductThumbnail" class="thumbnail" style="width:100px; height:100px;">
                    </div>
                    <div class="col-lg-4 ml-5 basketitem mt-2">
                        <a href="#">
                            @product.ProductName
                            <p class="myp"> @product.ProductDetail.ShortDesc</p>
                        </a>
                        <p class="myp"> @product.SKU</p>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <select class="custom-select" data-id="@product.SKU">
                                @for(int i=0; i<product.UnitOnOrder; i++)
                                {
                                    if (i != product.UnitsInStock)
                                    {
                                        <option value="@i">@i</option>
                                    }
                                    else
                                    {
                                        <option value="@i" selected>@i</option>
                                    }
                                }
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <strong><span id="unitprice"> @product.UnitPrice </span></strong>
                        <button type="button" class="btn btn-danger mt-3 btdelete" data-id="@product.SKU" id="btdelete">  Remove </button>
                    </div>
                </div>
            </div>
        }

    }
</div>

<script>
    $(document).on('change', '.custom-select', function () {
        var productSku = $(this).attr('data-id');
        var optionSelected = $(this).find("option:selected");
        var qty = optionSelected.text();
        $.ajax({
            type: "POST",
            url: '@Url.Action("UpdateProduct", "Shop")',
            data:
            {
                productSku: productSku,
                qty:qty
            },
            dataType: "json",
            success: function (response) {

            },
            error: function (response) {

            }
        });

    });
</script>

BAZARKA.WEB/Views/Shop/MiniBasket.mobile.cshtml
<div class="container">


    @model List<Product>
    @{
        if (Model != null && Model.Count() > 0)
        {
            <div class="m-0 p-0 bg-white"> <h4 class="m-0 p-0"> You have @Model.Count() items.</h4> </div>
        }
        else
        {
            <div class="m-0 p-0 bg-white"> <h4 class="m-0 p-0"> Your basket is empty </h4> </div>
        }
    }

    <div class="myScroll">
        @if (Model != null && Model.Count() > 0)
        {


            foreach (var product in Model)
            {
                <div id="@product.SKU">
                    <div class="row bg-white m-1 greyborder">
                        <div class="col-2">
                            <img src="@product.ProductThumbnail" class="" style="width:100px; height:100px;">
                        </div>
                        <div class="col-4 ml-5 basketitem mt-2">
                            <a href="#">
                                @product.ProductName
                                <p class="myp overflow-hidden"> @product.ProductDetail.ShortDesc</p>
                            </a>
                            <p class="myp overflow-hidden"> @product.SKU</p>
                        </div>


                        <div class="col-3">
                            <div class="form-group">
                                <select class="custom-select">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="1">4</option>
                                    <option value="2">5</option>
                                    <option value="3">6</option>
                                    <option value="1">7</option>
                                    <option value="2">8</option>
                                    <option value="3">9</option>
                                </select>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    <strong><span> Rs. @product.UnitPrice </span> </strong>
                                    <button type="button" class="btn btn-danger mt-3 btdelete" data-id="@product.SKU" id="btdelete">  Remove </button>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            }

        }
    </div>

    <script>
        $(document).on('click', '#btdelete', function () {
            var productSku = $(this).attr('data-id');
            swal({
                title: "Are you sure?",
                text: "Remove product from cart!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("RemoveProduct", "Shop")',
                        data: { productSku: productSku },
                        dataType: "json",
                        success: function (response) {
                            $('.RenderProducts').load(@{Html.RenderAction("MiniBasket", "Shop");});
                            //$('#' + productSku).html(' ');
                        },
                        error: function (response) {
                            alert(response.responseText);
                        }
                    });
                    swal("Item removed!", {
                        icon: "success",
                        buttons: false
                    });
                } else {
                    swal("Your imaginary file is safe!");
                }
            });
    });
    </script>

</div>

BAZARKA.WEB/Views/Shop/OrderSummary.cshtml
@*@model BAZARKA.CORE.ViewModels.VM_OrderSummary*@
<div class="col-lg-4 greyborder mt-4">
    <div class="col-lg-12 border-bottom">
        <h4 class="myh3"> Order summary </h4>

        <div class="row m-0 p-0">
            <div class="col-lg-8 m-0 p-0">
                <p class="myp"> Merchandise subtotal</p>
            </div>
            <div class="col-lg-4 m-0 p-0">
                @*<h4 class="myh4"> @Model.MerchandiseSubTotal Pkr</h4>*@
                <h4 class="myh4"> @BAZARKA.CORE.ViewModels.VM_OrderSummary.MerchandiseSubTotal Pkr</h4>

            </div>
        </div>

        <div class="row m-0 p-0">
            <div class="col-lg-8 m-0 p-0">
                <p class="myp"> Shipping and Handling</p>
            </div>
            <div class="col-lg-4 m-0 p-0">
                @*<h4 class="myh4"> @Model.Shipping </h4>*@
                <h4 class="myh4"> @BAZARKA.CORE.ViewModels.VM_OrderSummary.Shipping</h4>
            </div>
        </div>

        <div class="row m-0 p-0">
            <div class="col-lg-8 m-0 p-0">
                <p class="myp"> Tax </p>
            </div>
            <div class="col-lg-4 m-0 p-0">
                @*<h4 class="myh4"> @Model.Tax </h4>*@
                <h4 class="myh4"> @BAZARKA.CORE.ViewModels.VM_OrderSummary.Tax </h4>
            </div>
        </div>
    </div>
    <div class="col-lg-12 border-bottom">
        <div class="row m-0 p-0">
            <div class="col-lg-8 m-0 p-0">
                <h4 class="myh4"> Estimated total</h4>
            </div>
            <div class="col-lg-4 m-0 p-0">
                @*<h4 class="myh4"> @Model.EstimatedTotal </h4>*@
                <h4 class="myh4"> @BAZARKA.CORE.ViewModels.VM_OrderSummary.EstimatedTotal </h4>
            </div>
            <p class="myp"> Shipping & taxes calculated during checkout </p>
        </div>
    </div>
    <div class="col-lg-12 border-bottom">
        <div class="row m-0 p-0">
            <div class="col-lg-4 m-0 p-0">
            </div>
            <div class="col-lg-8 m-0 p-0 text-right">
                <button type="button" class="btn btn-link iblack" data-toggle="modal" data-target="#myModal">
                    View Promo Codes
                    <i class="fas fa-arrow-right iblack"></i>
                </button>
            </div>
            <div class="col-lg-12 m-0 p-0">
                <input type="text" placeholder="Promo or reward code" class="w-100 border p-2">
            </div>
            <div class="modal fade" id="myModal">
                <div class="modal-dialog">
                    <div class="modal-content white">
                        <!-- Modal Header -->
                        <!-- <div class="modal-header  w-100">
                          <h4 class="modal-title">Modal Heading</h4>
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div> -->
                        <!-- Modal body -->

                        <button type="button" class="btn btn-link iblack" data-dismiss="modal">
                            Promotion Codes
                            <i class="fas fa-arrow-left"></i>
                        </button>

                        <div class="modal-body">

                            <h3>   Bazarka Promotions </h3>
                            <p>
                                Occasionally Bazarka.pk offers promotions through e-mails, catalogs, and advertisements. You will always receive free shipping on U.S. merchandise orders over $50. As a registered member of Sephora.com, you may be eligible from time to time to receive e-mail promotions and offers that include special codes for special free samples, free shipping, or other promotions.

                                **Please note that excessive abuse or misuse of promotions and codes may result in order or item cancellation. In order to allow fair redemption and distribution of promotions to all of our registered clients, Sephora may restrict redemption to one per client.

                            </p>
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a href="@Url.Action("Checkout","Shop")">
        <div class="col-lg-12">
            <button class="btn btn-danger w-100"> CHECK OUT </button>
        </div>
    </a>
    <div class="col-lg-12">
        <div id="paypal-button-container"></div>

        <!-- Include the PayPal JavaScript SDK -->
        @*<script src="https://www.paypal.com/sdk/js?client-id=sb&currency=USD"></script>*@

        @*<script>
                // Render the PayPal button into #paypal-button-container
                paypal.Buttons({

                    // Set up the transaction
                    createOrder: function (data, actions) {
                        return actions.order.create({
                            purchase_units: [{
                                amount: {
                                    value: '0.01'
                                }
                            }]
                        });
                    },

                    // Finalize the transaction
                    onApprove: function (data, actions) {
                        return actions.order.capture().then(function (details) {
                            // Show a success message to the buyer
                            alert('Transaction completed by ' + details.payer.name.given_name + '!');
                        });
                    }


                }).render('#paypal-button-container');
            </script>*@

    </div>
</div>

BAZARKA.WEB/Views/Shop/OrderSummary.mobile.cshtml
@{
    var Total = ViewBag.Total;
    var Shipping = ViewBag.Shipping;
    var Tax = ViewBag.Tax;
}
<div class="container">
    <div class="col-12 bg-white border-bottom">
        <h4 class="myh3"> Order summary </h4>

        <div class="row bg-white m-0 p-0">
            <div class="col-8 m-0 p-0">
                <p class="myp"> Merchandise subtotal</p>
            </div>
            <div class="col-4 m-0 p-0">
                <h4 class="myh4"> @Total Pkr</h4>
            </div>
        </div>

        <div class="row bg-white m-0 p-0">
            <div class="col-8 m-0 p-0">
                <p class="myp"> Shipping and Handling</p>
            </div>
            <div class="col-4 m-0 p-0">
                <h4 class="myh4"> @Shipping </h4>
            </div>
        </div>

        <div class="row bg-white m-0 p-0">
            <div class="col-8 m-0 p-0">
                <p class="myp"> Tax </p>
            </div>
            <div class="col-4 m-0 p-0">
                <h4 class="myh4"> @Tax</h4>
            </div>
        </div>
    </div>
    <div class="col-12 bg-white border-bottom">
        <div class="row m-0 p-0">
            <div class="col-8 m-0 p-0">
                <h4 class="myh4"> Estimated total</h4>
            </div>
            <div class="col-4 m-0 p-0">

                <h4 class="myh4"> @Total </h4>
            </div>
            <p class="myp"> Shipping & taxes calculated during checkout </p>
        </div>
    </div>
    <div class="bg-white col-lg-12 border-bottom">
        <div class="row m-0 p-0">
            <div class="col-lg-4 m-0 p-0">
            </div>
            <div class="col-lg-8 m-0 p-0 text-right">
                <button type="button" class="btn btn-link iblack" data-toggle="modal" data-target="#myModal">
                    View Promo Codes
                    <i class="fas fa-arrow-right iblack"></i>
                </button>
            </div>
            <div class="bg-white col-lg-12 m-0 p-0">
                <input type="text" placeholder="Promo or reward code" class="w-100 border p-2">
            </div>
            <div class="modal fade" id="myModal">
                <div class="modal-dialog">
                    <div class="modal-content white">
                        <!-- Modal Header -->
                        <!-- <div class="modal-header  w-100">
                          <h4 class="modal-title">Modal Heading</h4>
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div> -->
                        <!-- Modal body -->

                        <button type="button" class="btn btn-link iblack" data-dismiss="modal">
                            Promotion Codes
                            <i class="fas fa-arrow-left"></i>
                        </button>

                        <div class="modal-body">

                            <h3>   Bazarka Promotions </h3>
                            <p>
                                Occasionally Bazarka.pk offers promotions through e-mails, catalogs, and advertisements. You will always receive free shipping on U.S. merchandise orders over $50. As a registered member of Sephora.com, you may be eligible from time to time to receive e-mail promotions and offers that include special codes for special free samples, free shipping, or other promotions.

                                **Please note that excessive abuse or misuse of promotions and codes may result in order or item cancellation. In order to allow fair redemption and distribution of promotions to all of our registered clients, Sephora may restrict redemption to one per client.

                            </p>
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="bg-white col-lg-12">
        <button class="btn btn-danger w-100" onclick="@Url.Action("Checkout","Shop")"> CHECK OUT </button>
    </div>
    <div class="col-lg-12">
        <div id="paypal-button-container"></div>

        <!-- Include the PayPal JavaScript SDK -->
        @*<script src="https://www.paypal.com/sdk/js?client-id=sb&currency=USD"></script>*@

        @*<script>
                // Render the PayPal button into #paypal-button-container
                paypal.Buttons({

                    // Set up the transaction
                    createOrder: function (data, actions) {
                        return actions.order.create({
                            purchase_units: [{
                                amount: {
                                    value: '0.01'
                                }
                            }]
                        });
                    },

                    // Finalize the transaction
                    onApprove: function (data, actions) {
                        return actions.order.capture().then(function (details) {
                            // Show a success message to the buyer
                            alert('Transaction completed by ' + details.payer.name.given_name + '!');
                        });
                    }


                }).render('#paypal-button-container');
            </script>*@

    </div>
</div>